# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ordersigner.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ordersigner.proto',
  package='ordersigner',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11ordersigner.proto\x12\x0bordersigner\"\x8b\x02\n\x10SignOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\r\x12\x0e\n\x06market\x18\x02 \x01(\t\x12*\n\norder_side\x18\x03 \x01(\x0e\x32\x16.ordersigner.OrderSide\x12*\n\norder_type\x18\x04 \x01(\x0e\x32\x16.ordersigner.OrderType\x12\x0e\n\x06\x61mount\x18\x05 \x01(\t\x12\r\n\x05price\x18\x06 \x01(\t\x12\x13\n\x0bquote_limit\x18\x07 \x01(\t\x12\x11\n\ttaker_fee\x18\x08 \x01(\t\x12\x11\n\tmaker_fee\x18\t \x01(\t\x12\x11\n\tpost_only\x18\n \x01(\x08\x12\x11\n\tsignature\x18\x0b \x01(\t\"&\n\x11SignOrderResponse\x12\x11\n\tsignature\x18\x01 \x01(\t*\x1d\n\tOrderSide\x12\x07\n\x03\x41SK\x10\x00\x12\x07\n\x03\x42ID\x10\x01*\"\n\tOrderType\x12\t\n\x05LIMIT\x10\x00\x12\n\n\x06MARKET\x10\x01\x32[\n\x0bOrderSigner\x12L\n\tSignOrder\x12\x1d.ordersigner.SignOrderRequest\x1a\x1e.ordersigner.SignOrderResponse\"\x00\x62\x06proto3'
)

_ORDERSIDE = _descriptor.EnumDescriptor(
  name='OrderSide',
  full_name='ordersigner.OrderSide',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ASK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BID', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=344,
  serialized_end=373,
)
_sym_db.RegisterEnumDescriptor(_ORDERSIDE)

OrderSide = enum_type_wrapper.EnumTypeWrapper(_ORDERSIDE)
_ORDERTYPE = _descriptor.EnumDescriptor(
  name='OrderType',
  full_name='ordersigner.OrderType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LIMIT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MARKET', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=375,
  serialized_end=409,
)
_sym_db.RegisterEnumDescriptor(_ORDERTYPE)

OrderType = enum_type_wrapper.EnumTypeWrapper(_ORDERTYPE)
ASK = 0
BID = 1
LIMIT = 0
MARKET = 1



_SIGNORDERREQUEST = _descriptor.Descriptor(
  name='SignOrderRequest',
  full_name='ordersigner.SignOrderRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='ordersigner.SignOrderRequest.user_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='market', full_name='ordersigner.SignOrderRequest.market', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='order_side', full_name='ordersigner.SignOrderRequest.order_side', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='order_type', full_name='ordersigner.SignOrderRequest.order_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='ordersigner.SignOrderRequest.amount', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='ordersigner.SignOrderRequest.price', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quote_limit', full_name='ordersigner.SignOrderRequest.quote_limit', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taker_fee', full_name='ordersigner.SignOrderRequest.taker_fee', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maker_fee', full_name='ordersigner.SignOrderRequest.maker_fee', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='post_only', full_name='ordersigner.SignOrderRequest.post_only', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='ordersigner.SignOrderRequest.signature', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=302,
)


_SIGNORDERRESPONSE = _descriptor.Descriptor(
  name='SignOrderResponse',
  full_name='ordersigner.SignOrderResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature', full_name='ordersigner.SignOrderResponse.signature', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=342,
)

_SIGNORDERREQUEST.fields_by_name['order_side'].enum_type = _ORDERSIDE
_SIGNORDERREQUEST.fields_by_name['order_type'].enum_type = _ORDERTYPE
DESCRIPTOR.message_types_by_name['SignOrderRequest'] = _SIGNORDERREQUEST
DESCRIPTOR.message_types_by_name['SignOrderResponse'] = _SIGNORDERRESPONSE
DESCRIPTOR.enum_types_by_name['OrderSide'] = _ORDERSIDE
DESCRIPTOR.enum_types_by_name['OrderType'] = _ORDERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SignOrderRequest = _reflection.GeneratedProtocolMessageType('SignOrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _SIGNORDERREQUEST,
  '__module__' : 'ordersigner_pb2'
  # @@protoc_insertion_point(class_scope:ordersigner.SignOrderRequest)
  })
_sym_db.RegisterMessage(SignOrderRequest)

SignOrderResponse = _reflection.GeneratedProtocolMessageType('SignOrderResponse', (_message.Message,), {
  'DESCRIPTOR' : _SIGNORDERRESPONSE,
  '__module__' : 'ordersigner_pb2'
  # @@protoc_insertion_point(class_scope:ordersigner.SignOrderResponse)
  })
_sym_db.RegisterMessage(SignOrderResponse)



_ORDERSIGNER = _descriptor.ServiceDescriptor(
  name='OrderSigner',
  full_name='ordersigner.OrderSigner',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=411,
  serialized_end=502,
  methods=[
  _descriptor.MethodDescriptor(
    name='SignOrder',
    full_name='ordersigner.OrderSigner.SignOrder',
    index=0,
    containing_service=None,
    input_type=_SIGNORDERREQUEST,
    output_type=_SIGNORDERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORDERSIGNER)

DESCRIPTOR.services_by_name['OrderSigner'] = _ORDERSIGNER

# @@protoc_insertion_point(module_scope)
