version: '3.4'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes: 
      - ./configs/proxy.conf:/etc/nginx/conf.d/proxy.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8765:8765"
  grpcgateway:
    image: lispczz/grpc-dynamic-gateway:latest
    container_name: grpc_dynamic_gateway
    restart: always
    volumes:
      - ../proto/exchange/matchengine.proto:/api.proto
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "50052:50052"
    command: api.proto -I ../../.. -p 50052 -g host.docker.internal:50051 -m /api    
  db:
    image: timescale/timescaledb:2.1.0-pg13
    container_name: exchange_pq
    restart: always
    volumes:
      - ./data/volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: exchange
      POSTGRES_USER: exchange
      POSTGRES_PASSWORD: exchange_AA9944

  zookeeper:
    image: zookeeper
    container_name: exchange_zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - ./data/volumes/log_zookeeper:/var/log/zookeeper

  kafka:
    image: wurstmeister/kafka:latest
    container_name: exchange_kafka
    restart: always
    logging:
      options:
        max-size: 10m
    ports:
      - "9092:9092"
    volumes:
      - ./data/volumes/log_kafka:/var/log/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "trades:1:1,orders:1:1,balances:1:1,registeruser:1:1,unifyevents:1:1"
