name: CI

on:
  push:
    branches:
      - master
      - prod
      - release/*
  pull_request:
    branches:
      - master
      - prod
      - release/*

jobs:
  integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libcurl4-openssl-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.90.0

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node_modules
        id: npm_cache
        uses: actions/cache@v4
        with:
          path: ./examples/js/node_modules
          key: node_modules-${{ hashFiles('examples/js/package-lock.json') }}

      - name: npm ci
        if: steps.npm_cache.outputs.cache-hit != 'true'
        run: |
          cd ./examples/js/
          npm ci

      - name: Pull git submodule
        run: git submodule update --init --recursive

      - name: Up docker compose
        run: docker compose --file "./orchestra/docker/docker-compose.yaml" up --detach

      - name: Start exchange server daemon
        run: make startall

      - name: Check services status
        run: |
          sleep 5
          make taillogs
          docker compose --file "./docker/docker-compose.yaml" logs --tail=20

      - name: Run trading tests
        run: |
          cd ./examples/js/
          npx ts-node trade.ts
          sleep 5
          npx ts-node print_orders.ts
          npx ts-node tests/transfer.ts
          npx ts-node tests/put_batch_orders.ts
