name: CI

on:
  push:
    branches:
      - master
      - prod
      - release/*
  pull_request:
    branches:
      - master
      - prod
      - release/*

jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly

    steps:
      - name: Install libpq
        uses: sudo apt-get install libpq-dev

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
