name: CI

on:
  push:
    branches:
      - master
      - prod
      - release/*
  pull_request:
    branches:
      - master
      - prod
      - release/*

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.53.0

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo target
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Install 1.53.0 toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.53.0
          override: true
          components: rustfmt, clippy
      
      - name: Run "cargo fmt & check"
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      
      - name: Run "cargo clippy"
        uses: actions-rs/cargo@v1
        # continue-on-error: true
        with:
          command: clippy
          args: -- -D warnings

      - name: Install Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          # cache: 'npm'
          # cache-dependency-path: examples/js/package-lock.json

      - name: Prettify js/ts code
        uses: creyD/prettier_action@v4.0
        with:
          dry: True
          prettier_options: --check examples/*
          # github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache node_modules
        id: npm_cache
        uses: actions/cache@v2
        with:
          path: ./examples/js/node_modules
          key: node_modules-${{ hashFiles('examples/js/package-lock.json') }}

      - name: npm ci
        if: steps.npm_cache.outputs.cache-hit != 'true'
        run: |
          cd ./examples/js/
          npm ci

      - run: npx eslint src/
