name: CI

on:
  push:
    branches:
      - master
      - prod
      - release/*
  pull_request:
    branches:
      - master
      - prod
      - release/*

jobs:
  rust-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install protobuf compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.90.0
        with:
          components: rustfmt, clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all-targets -- -D warnings

  js-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node_modules
        id: npm_cache
        uses: actions/cache@v4
        with:
          path: examples/js/node_modules
          key: node_modules-${{ hashFiles('examples/js/package-lock.json') }}

      - name: npm ci
        if: steps.npm_cache.outputs.cache-hit != 'true'
        run: |
          cd examples/js/
          npm ci

      - name: Prettify js/ts code
        run: |
          cd examples/js/
          npx prettier --check "**/*.{js,ts}"
