name: CI

on:
  push:
    branches:
      - master
      - prod
      - release/*
  pull_request:
    branches:
      - master
      - prod
      - release/*

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libcurl4-openssl-dev

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@1.90.0

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Run cargo test
        run: cargo test --all-targets
