name: CI

on:
  push:
    branches:
      - master
      - prod
      - release/*
  pull_request:
    branches:
      - master
      - prod
      - release/*

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Run "cargo test"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --

#      - name: Run "cargo bench"
#        uses: actions-rs/cargo@v1
#        with:
#          command: bench
#          args: --
